package io.poc.inventoryservice.model;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.*;

import java.util.List;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class OrderDto {

    // Usually generated by system, so optional on create.
    private Long orderId;

    @NotEmpty(message = "Order must contain at least one item")
    @Valid
    private List<OrderItemDto> items;

    @NotNull(message = "User ID is mandatory")
    private Long userId;

    private Long orderValue;

    @NotBlank(message = "Order status is mandatory")
    private String orderStatus;

    @NotBlank(message = "Email is mandatory")
    @Email(message = "Email must be valid")
    private String email;

}