server:
  port: 8081

spring:
  application:
    name: gatewayservice

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: http://localhost:8082
              predicates:
                - Path=/inventory-service/**
              filters:
                - RewritePath=/inventory-service/(?<segment>.*),/api/v1/inventory-service/${segment}


            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/order-service/**
              filters:
                - RewritePath=/order-service/(?<segment>.*),/api/v1/order-service/${segment}


            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/payment-service/**
              filters:
                - RewritePath=/payment-service/(?<segment>.*),/api/v1/payment-service/${segment}


            - id: notification-service
              uri: http://localhost:8085
              predicates:
                - Path=/notification-service/**
              filters:
                - RewritePath=/notification-service/(?<segment>.*),/api/v1/notification-service/${segment}